/**
 * FR-08: Package Distribution
 * 
 * Requirement: The library shall be structured as a valid npm and composer package 
 * that can be installed and imported in JavaScript, TypeScript and PHP projects.
 */

import { describe, it, expect } from 'vitest';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';

const rootDir = join(__dirname, '../..');
const pkg = JSON.parse(readFileSync(join(rootDir, 'package.json'), 'utf8'));

describe('FR-08: Package Distribution', () => {
  
  // AC-1: A valid package.json exists with correct main and module entry points.
  it('AC-1: main, module, types and exports point at files the build emits', () => {
    const entryPoints = [
      pkg.main,
      pkg.module,
      pkg.types,
      pkg.exports['.'].import,
      pkg.exports['.'].require,
      pkg.exports['.'].types,
    ];
    for (const entryPoint of entryPoints) {
      expect(entryPoint, 'entry point must be declared').toBeTruthy();
      expect(existsSync(join(rootDir, entryPoint)), `${entryPoint} is missing from the build output`).toBe(true);
    }
  });

  // AC-2: The package can be installed via npm install from a registry or a Git repository.
  it('AC-2: every declared entry point is inside a packed directory', () => {
    const packed: string[] = pkg.files;
    for (const entryPoint of [pkg.main, pkg.module, pkg.types]) {
      expect(packed.some((f) => entryPoint.replace(/^\.\//, '').startsWith(f))).toBe(true);
    }
  });

  // AC-3: ES module imports work.
  it('AC-3: ES module imports work', async () => {
    const { AIFormFill } = await import('../../lib/core/aiFormFill');
    expect(AIFormFill).toBeDefined();
  });

  // AC-4: TypeScript type declarations are included in or generated by the package.
  it('AC-4: TypeScript types are available', async () => {
    const types = await import('../../lib/core/types');
    
    // Verify type exports exist (they compile correctly)
    expect(types).toBeDefined();
  });
});
